apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: udaconnect
build:
  artifacts:
  - image: rne1223/udaconnect-api
    context: modules/api
    docker:
      dockerfile: Dockerfile
  - image: rne1223/udaconnect-person-service
    context: modules/person-service
    docker:
      dockerfile: Dockerfile
  - image: rne1223/udaconnect-webapp
    context: modules/webapp
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
#    - argocd/argocd-server-nodeport.yml
#    - argocd/udaconnect-application.yml
    - manifest/db-configmap.yaml
    - manifest/db-secret.yaml
    - manifest/postgres.yaml
    - manifest/udaconnect-api.yaml
    - manifest/udaconnect-person-service.yaml
    - manifest/udaconnect-webapp.yaml
