apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-webapp
  name: udaconnect-webapp
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    service: udaconnect-webapp
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-webapp
  name: udaconnect-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-webapp
  template:
    metadata:
      labels:
        service: udaconnect-webapp
    spec:
      containers:
      - image: rne1223/udaconnect-webapp:latest
        name: udaconnect-webapp
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
