apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-service
  name: udaconnect-location-service
spec:
  ports:
  - name: "5005"
    port: 5002
    targetPort: 5005
    nodePort: 30003
  - name: "attach-port"
    port: 5679
    targetPort: 5678 
    nodePort: 30805
  selector:
    service: udaconnect-location-service 
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-service 
  name: udaconnect-location-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-service 
  template:
    metadata:
      labels:
        service: udaconnect-location-service 
    spec:
      containers:
      - image: rne1223/udaconnect-location-service:latest
        name: udaconnect-location-service 
        imagePullPolicy: Always 
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
