apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-person-service
  name: udaconnect-person-service
spec:
  ports:
  - name: "5000"
    port: 5001
    targetPort: 5000
    nodePort: 30002
  - name: "attach-port"
    port: 5679
    targetPort: 5678 
    nodePort: 30004
  selector:
    service: udaconnect-person-service 
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-person-service 
  name: udaconnect-person-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-person-service 
  template:
    metadata:
      labels:
        service: udaconnect-person-service 
    spec:
      containers:
      - image: rne1223/udaconnect-person-service:latest
        name: udaconnect-person-service 
        imagePullPolicy: Always 
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
